version: '3.4'

services:
  mongodb.data:
    image: mongo
    ports:
      - "27017:27017"
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433" 
  vehicles.api:
    build: 
      context: ./src/Services/Vehicles/
      dockerfile: Dockerfile
    depends_on:
      - sql.data
    ports:
     - "5000:80"
  hotels.api:
    build:
      context: ./src/Services/Hotels/
      dockerfile: Dockerfile
    depends_on:
      - mongodb.data
    ports:
      - "8080:8080"