version: '3.4'

services:
  messagebroker:
    image: rabbitmq:3-management-alpine
    ports: 
      - "5672:5672"
      - "15672:15672"
  flights.data:
    image: redis:alpine
    ports:
      - "6379:6379"
  hotels.data:
    image: mongo
    ports:
      - "27017:27017"
  vehicles.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433" 
  vehicles.api:
    build: 
      context: ./src/Services/Vehicles/
      dockerfile: Dockerfile
    depends_on:
      - vehicles.data
      - messagebroker
    ports:
     - "8080:80"
  hotels.api:
    build:
      context: ./src/Services/Hotels/
      dockerfile: Dockerfile
    depends_on:
      - hotels.data
      - messagebroker
    ports:
      - "8081:8080"
  flights.api:
    build:
      context: ./src/Services/Flights/
      dockerfile: Dockerfile
    depends_on:
      - flights.data
      - messagebroker
    ports:
      - "8082:8080"